### PR TITLE
Improve the structure of the deprecations page

### PR DESCRIPTION
**Pull request by renetapopova**
Cherry-picked from #1348 and #1353

### CODE REVIEW

**Review by Hunterness — COMMENTED** [review]
This looks like a good cherry-pick but it doesn't seem to update the 5.0 one to follow format? Shouldn't there at least be a `Removed features` header like for 4.0?

**Comment by renetapopova** [comment]
> This looks like a good cherry-pick but it doesn't seem to update the 5.0 one to follow format? Shouldn't there at least be a `Removed features` header like for 4.0?

This one just cherry-picks the updates up to 4.4. Then, we should create another PR with the 5.0 changes, I guess when #1328 and #1340 are merged.

**Comment by Hunterness** [comment]
> This one just cherry-picks the updates up to 4.4. Then, we should create another PR with the 5.0 changes, I guess when #1328 and #1340 are merged.

Since #1340 is merged and #1328 is currently blocked on product pr and anyway needs rebasing and updating I think you could update the 5.0 changes here and then I'll fix #1328 based on all changes instead of it needing to be updated twice?

**Comment by renetapopova** [comment]
> > This one just cherry-picks the updates up to 4.4. Then, we should create another PR with the 5.0 changes, I guess when #1328 and #1340 are merged.
> 
> Since #1340 is merged and #1328 is currently blocked on product pr and anyway needs rebasing and updating I think you could update the 5.0 changes here and then I'll fix #1328 based on all changes instead of it needing to be updated twice?

OK, I'll do that.

**Review by Hunterness — APPROVED** [review]

**Pull request merged**
