### PR TITLE
Update heading level

### PR DESCRIPTION
**Pull request by recrwplay**
The headings are at level 4 but expected to be level 3 at the point where they are included.

### CODE REVIEW

**Comment by recrwplay** [comment]
[Address warnings in the Antora build](https://trello.com/c/Si0htooA/25-address-warnings-in-the-antora-build)

**Review by martin-neotech — APPROVED** [review]
Nice!

**Review by AlexicaWright — COMMENTED** [review]
Builds just fine, but it renders no differently than the currently published docs?

**Comment by recrwplay** [comment]
> Builds just fine, but it renders no differently than the currently published docs?

Yes, the html was forced to the correct header level by asciidoctor and a warning issued. This change just uses the correct level in the source so there is no warning in the build.

**Comment by AlexicaWright** [comment]
Ah, I see! Then 👍  from me!

**Pull request merged**
