### PR TITLE
Speeds up the build on macOS

### PR DESCRIPTION
**Pull request by ncordon**
## What
Speeds up the build on OSX systems, by using a file system in memory rather than in disk. The reason for that is that `sun.nio.ch.FileChannelImpl.force` is [10x times](https://bugs.openjdk.java.net/browse/JDK-8205162) slower in an OSX than in Linux. Hat tip to @zimmre.

Writing the database files to memory speeds up that.

## Why
The build was taking about 2 hours on a macOS compared to 20 minutes in Linux. After adding this changes, the build times have lowered to ~20 min in macOS:

Screenshot 2021-10-19 at 19 39 54

### CODE REVIEW

**Comment by MarkWoulfeNeo4j** [comment]
I have tested this and build times are greatly improved:

`mvn clean install` -> 20 mins
`mvn -T1C clean install` -> 10 mins 

🥳

**Comment by davidoliverSP2** [comment]
> I have tested this and build times are greatly improved:
> 
> `mvn clean install` -> 20 mins `mvn -T1C clean install` -> 10 mins
> 
> 🥳

Yep, this works for me too.

@ncordon Thank you very much! Is this PR viable for cherry picking back to earlier versions?

**Comment by ncordon** [comment]
> Is this PR viable for cherry picking back to earlier versions?

Probably, I'll try to give you a hand with that once the new database release is done 💃

**Review by martin-neotech — APPROVED** [review]
Thanks

**Pull request merged**
