### PR TITLE
Add documentation on how to use the fulltext schema indexes.

### PR DESCRIPTION
**Pull request by chrisvest**
Related to https://github.com/neo-technology/neo4j-manual-modeling/pull/605

### CODE REVIEW

**Comment by mariascharin** [comment]
@chrisvest I added some of the info about the new indexes from the Operations Manual PR and made it into an "Introduction" section. I also added a couple of links to the relevant sections of the Ops Man. 
WDYT?

**Comment by chrisvest** [comment]
@mariascharin These changes in both cypher and Ops manuals look great together!

**Comment by chrisvest** [comment]
Looks like a rebase went wrong.

**Comment by mariascharin** [comment]
@chrisvest You are right. Do you have a tip on how to fix it? I thought perhaps `git reflog` will help, or is there a better way?

**Pull request merged**
