### PR TITLE
Document discovery metrics in separate class

### PR DESCRIPTION
**Pull request by andrewkerr9000**

### CODE REVIEW

**Comment by andrewkerr9000** [comment]
https://github.com/neo-technology/neo4j/pull/6011

**Comment by davidoliverSP2** [comment]
[New Metrics in /status endpoint](https://trello.com/c/abFsgIMj/119-new-metrics-in-status-endpoint)

**Review by davidoliverSP2 — APPROVED** [review]
This builds green, and includes the change that fixes the build (as per #600 from @craigtaverner)

**Comment by davidoliverSP2** [comment]
Resubmitted as #602 due to partial duplication in the merged #600

**Pull request closed without merging**
