### PR TITLE
Fix doc tests according to new admin cli implementation

### PR DESCRIPTION
**Pull request by andreikoval**

### CODE REVIEW

**Review by davidoliverSP2 — APPROVED** [review]
Thanks @andreikoval 

This builds cleanly for me, so I'm happy. I think this would benefit from a technical peer review though, and in the absence of Jonatan, perhaps someone else from Kernel team could review?

Also, I note that `--mode` is removed in this PR. This would have impact on the Operations Manual, where it appears in these pages:
* https://neo4j.com/docs/operations-manual/4.0-preview/installation/linux/debian/ (step 1b)
* https://neo4j.com/docs/operations-manual/4.0-preview/upgrade/deployment-upgrading/ (step 3 of section 6.2.1)
* https://neo4j.com/docs/operations-manual/current/tools/import/options/
* https://neo4j.com/docs/operations-manual/current/tools/import/syntax/

**Comment by davidoliverSP2** [comment]
@klaren we currently don't have anyone in docs team available to do a technical review on this PR. Would you be able to take a look? many thanks

**Review by klaren — APPROVED** [review]

**Comment by andreikoval** [comment]
@davidoliverSP2 I think all of the pages mentioned above are already fixed in scope of neo-technology/neo4j-manual-modeling/pull/811

**Comment by andreikoval** [comment]
Oh, it looks like I missed two places  there, I'll fix it.

**Comment by andreikoval** [comment]
neo-technology/neo4j-manual-modeling/pull/827

**Pull request merged**
