### PR TITLE
Add fabric-specific clauses

### PR DESCRIPTION
**Pull request by mariascharin**

### CODE REVIEW

**Comment by mariascharin** [comment]
This goes together with https://github.com/neo-technology/neo4j-manual-modeling/pull/890

**Comment by mariascharin** [comment]
image

image

**Comment by mariascharin** [comment]
image

**Comment by mariascharin** [comment]
@sherfert 

I have added a section called "Correlated subqueries" to the "Subqueries" section - this is what I wanted your advice about earlier today, but I decided to put it in here so that you can have a look and say what you think! So I basically copied the content from Tobias's and Petr's doc. The first screenshot shows how the beginning of it looks on that page.

The second screenshot shows how the `USE` clause looks on the _Clauses_ page, and the third is how it looks on its own page. I guess we've already discussed and agreed on the looks, but I wanted to show it nevertheless.

**Review by sherfert — APPROVED** [review]
I think it makes sense how things are arranged!

**Pull request merged**
