### PR TITLE
coverted long value to needed string value

### PR DESCRIPTION
**Pull request by glindroth**

### CODE REVIEW

**Review by tinwelint — APPROVED** [review]

**Comment by davidoliverSP2** [comment]
Thanks @glindroth - do you know where does this change render in the docs (so I can test that it's updating correctly)

Also, could you confirm this is only required for version 5.0?

**Review by tinwelint — CHANGES_REQUESTED** [review]
The changes in Neo4jBasicDocTest and StartWithConfigurationDocTest are not correct. They should stay Long. It happens to be correct locally perhaps since you don't compile against latest neo4j HEAD

**Comment by glindroth** [comment]
> The changes in Neo4jBasicDocTest and StartWithConfigurationDocTest are not correct. They should stay Long. It happens to be correct locally perhaps since you don't compile against latest neo4j HEAD

I have reverted those changes. With that revert this builds locally at least.

**Review by tinwelint — APPROVED** [review]

**Review by davidoliverSP2 — APPROVED** [review]
👍 

thanks @glindroth & @tinwelint

**Pull request merged**
