### PR TITLE
Propose fix two typos

### PR DESCRIPTION
**Pull request by jeis2497052**
OK to remove trailing white space ?

### CODE REVIEW

**Comment by jjaderberg** [comment]
Thanks @jeis2497052!

Have you signed our Contributor License Agreement? If not, please see information at https://neo4j.com/developer/cla/. We require a CLA from everyone contributing code, to make sure there are no surprises or disputes about code ownership down the road. Details about the agreement and how to sign are on that page. When I see that we have a CLA from you I can merge this change.

Yes, removing trailing white space is fine.

**Comment by jeis2497052** [comment]
I will sign the CLA shortly

**Comment by jeis2497052** [comment]
CLA set via email per instructions

**Comment by jjaderberg** [comment]
@jeis2497052 Thank you!

**Pull request merged**
