### PR TITLE
Add default graph keyword to syntax, examples and refcard

### PR DESCRIPTION
**Pull request by hedengran**

### CODE REVIEW

**Comment by Hunterness** [comment]
I'm a bit confused as to why I have commits here?

**Comment by hedengran** [comment]
That is an excellent question @Hunterness. When I branched for this PR, I accidentally branched from your PR which I reviewed. I assume that it doesn't matter?

**Comment by Hunterness** [comment]
@hedengran probably not but I think it might be better to rebase on (or reset on top of) latest 4.2

It will also help Sascha know what things he need to review and which are old (but I guess all those with your face is for him so  :P)

**Comment by hedengran** [comment]
Wow, that was not better. Will sort this out.

**Review by SaschaPeukert — APPROVED** [review]

**Pull request merged**
