### PR TITLE
Upgrade to 4.1.8-SNAPSHOT

### PR DESCRIPTION
**Pull request by fabiim**

### CODE REVIEW

**Review by martin-neotech — APPROVED** [review]
Thanks

**Comment by fabiim** [comment]
@martin-neotech thanks for the review,  I don't have permissions to merge, can you do it?

**Comment by martin-neotech** [comment]
Yes I can merge. Not at the computer right now.

**Comment by fabiim** [comment]
thank you!

**Comment by martin-neotech** [comment]
Dependency of https://github.com/neo-technology/neo4j/pull/9211

**Pull request merged**
