### PR TITLE
Add examples for failing to create already existing indexes and constraints

### PR DESCRIPTION
**Pull request by Hunterness**
Do we want to add these tests in older versions as well? And if so, how far back?

### CODE REVIEW

**Comment by Hunterness** [comment]
[Can we add the type of exception that will be thrown to 5.4 Constraints?](https://trello.com/c/PywLaToe/2600-can-we-add-the-type-of-exception-that-will-be-thrown-to-54-constraints)

**Review by davidoliverSP2 — APPROVED** [review]
This looks good, thanks @Hunterness 

As already discussed, the generated code examples is including a `copy to clipboard` option on the error message, which I don't think is useful (see screenshot example). 

If it's possible to add `role=nocopy` to the codeblock attributes, then that should resolve it, otherwise we can raise another card to investigate.

Screenshot 2021-09-20 at 12 49 40

**Comment by davidoliverSP2** [comment]
Thanks @Hunterness - the last commit was successful in removing the `copy to clipboard` option from the error messages!
Screenshot 2021-09-20 at 16 07 47

**Review by nadja-muller — APPROVED** [review]

**Comment by Hunterness** [comment]
@davidoliverSP2 (and @nadja-muller), do we want to backport this to earlier versions as well? If so, from when?

(some syntax needs to be updated to previous versions but should not be hard to backport)

(DECISION: no backporting at this point in time)

**Pull request merged**
